#!/usr/bin/env python3
"""
Migration script to add AI token tracking fields to changelogs table

This migration adds:
- ai_input_tokens: Number of input tokens used for AI analysis
- ai_output_tokens: Number of output tokens generated by AI

Run this script to add the new columns to the existing changelogs table.
"""
import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from sqlalchemy import inspect, text, Integer
from app.database import engine


def column_exists(table_name: str, column_name: str) -> bool:
    """Check if a column exists in a table"""
    inspector = inspect(engine)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def add_token_columns():
    """Add the token tracking columns to changelogs table"""
    added = []
    
    with engine.connect() as conn:
        # Add ai_input_tokens column
        if not column_exists('changelogs', 'ai_input_tokens'):
            conn.execute(text(
                "ALTER TABLE changelogs ADD COLUMN ai_input_tokens INTEGER"
            ))
            conn.commit()
            added.append('ai_input_tokens')
            print("  Added column: ai_input_tokens")
        else:
            print("  Column ai_input_tokens already exists, skipping")
        
        # Add ai_output_tokens column
        if not column_exists('changelogs', 'ai_output_tokens'):
            conn.execute(text(
                "ALTER TABLE changelogs ADD COLUMN ai_output_tokens INTEGER"
            ))
            conn.commit()
            added.append('ai_output_tokens')
            print("  Added column: ai_output_tokens")
        else:
            print("  Column ai_output_tokens already exists, skipping")
    
    return added


def run_migration():
    """Run the complete migration"""
    print("\n" + "=" * 60)
    print("AI Token Tracking Migration")
    print("=" * 60)
    
    print("\nAdding token tracking columns to changelogs table...")
    added = add_token_columns()
    
    print("\n" + "=" * 60)
    if added:
        print(f"Migration completed! Added {len(added)} column(s): {', '.join(added)}")
    else:
        print("Migration completed! No changes needed.")
    print("=" * 60)
    print()


if __name__ == "__main__":
    run_migration()
