"""
ChangeLog model for tracking database changes with AI-generated descriptions
"""
from datetime import datetime
from sqlalchemy import String, Integer, ForeignKey, DateTime, Text, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship
from .base import Base, TimestampMixin


class ChangeLog(Base, TimestampMixin):
    """
    Change Log Entry
    
    Stores information about each sync/commit including:
    - GitHub commit details
    - Change statistics
    - AI-generated descriptions (in German)
    - Full diff for reference
    """
    __tablename__ = "changelogs"

    id: Mapped[int] = mapped_column(primary_key=True)
    
    # Relationship to Database
    database_id: Mapped[int] = mapped_column(
        ForeignKey("databases.id", ondelete="CASCADE"), 
        nullable=False, 
        index=True
    )
    
    # GitHub Commit Information
    commit_sha: Mapped[str] = mapped_column(String(40), nullable=False, index=True)
    commit_date: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    commit_message: Mapped[str] = mapped_column(Text, nullable=False)
    commit_url: Mapped[str | None] = mapped_column(String(500), nullable=True)
    
    # Change Statistics
    files_changed: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    additions: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    deletions: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    
    # AI-Generated Content (German language)
    ai_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    """Short summary of changes (1-2 sentences, German)"""
    
    ai_details: Mapped[str | None] = mapped_column(Text, nullable=True)
    """Detailed description of changes (Markdown format, German)"""
    
    ai_provider: Mapped[str | None] = mapped_column(String(50), nullable=True)
    """Which AI provider was used (claude, openai, gemini)"""
    
    ai_model: Mapped[str | None] = mapped_column(String(100), nullable=True)
    """Which model was used for generation"""
    
    ai_generated_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    """When the AI analysis was performed"""
    
    ai_error: Mapped[str | None] = mapped_column(Text, nullable=True)
    """Error message if AI analysis failed"""
    
    ai_input_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    """Number of input tokens used for AI analysis"""
    
    ai_output_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    """Number of output tokens generated by AI"""
    
    ai_input_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    """Number of input tokens used for AI analysis"""
    
    ai_output_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    """Number of output tokens generated by AI"""
    
    # Raw Data (complete storage)
    diff_patch: Mapped[str | None] = mapped_column(Text, nullable=True)
    """Full diff/patch content from GitHub"""
    
    changed_items: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    """
    Structured list of changed items:
    [
        {
            "table": "Rechnungen",
            "field": "Summe",
            "code_type": "fn",
            "change_type": "modified",  # added, modified, deleted
            "additions": 5,
            "deletions": 2
        },
        ...
    ]
    """
    
    # Relationships
    database: Mapped["Database"] = relationship("Database", back_populates="changelogs")

    def __repr__(self) -> str:
        return f"<ChangeLog(id={self.id}, database_id={self.database_id}, sha='{self.commit_sha[:8]}...', date={self.commit_date})>"
    
    @property
    def has_ai_analysis(self) -> bool:
        """Check if AI analysis was performed"""
        return self.ai_summary is not None or self.ai_details is not None
    
    @property
    def total_changes(self) -> int:
        """Total number of line changes"""
        return self.additions + self.deletions
    
    @property
    def short_sha(self) -> str:
        """First 7 characters of commit SHA"""
        return self.commit_sha[:7] if self.commit_sha else ""
    
    @property
    def changed_tables(self) -> list:
        """List of unique table names that were changed"""
        if not self.changed_items:
            return []
        tables = set()
        for item in self.changed_items:
            if isinstance(item, dict) and 'table' in item:
                tables.add(item['table'])
        return sorted(list(tables))
    
    @property
    def change_summary_text(self) -> str:
        """Generate a simple text summary of changes"""
        parts = []
        if self.files_changed:
            parts.append(f"{self.files_changed} Datei(en)")
        if self.additions:
            parts.append(f"+{self.additions}")
        if self.deletions:
            parts.append(f"-{self.deletions}")
        return ", ".join(parts) if parts else "Keine Änderungen"
    
    @property
    def total_tokens(self) -> int:
        """Total number of tokens used (input + output)"""
        return (self.ai_input_tokens or 0) + (self.ai_output_tokens or 0)
    
    @property
    def has_token_info(self) -> bool:
        """Check if token usage information is available"""
        return self.ai_input_tokens is not None or self.ai_output_tokens is not None
    
    @property
    def token_summary_text(self) -> str:
        """Generate a token usage summary"""
        if not self.has_token_info:
            return ""
        parts = []
        if self.ai_input_tokens:
            parts.append(f"↓{self.ai_input_tokens}")
        if self.ai_output_tokens:
            parts.append(f"↑{self.ai_output_tokens}")
        return " ".join(parts)
